projectName: sample
source: cai-commerce-external-channel-services
iam:
  codebuildRole:
    principalServices:
      - "codebuild"
    allowActions:
      s3:
        actions:
          - 'GetObject'
          - 'GetBucket'
          - 'List*'
          - 'DeleteObject'
          - 'Abort'
          - 'PutObject'
        resources:
          - '*'
      codecommit:
        actions:
          - '*'
        resources:
          - '*'
      sts:
        actions:
          - 'AssumeRole'
        resources:
          - '*'
      codepipeline:
        actions:
          - 'GetPipelineState'
          - 'PutApprovalResult'
        resources:
          - '*'
codebuilds:
  - projectName: test
    buildSpecYaml: buildspec-test.yml
  - projectName: deploy
    buildSpecYaml: buildspec-deploy.yml
