projectName: "orchestrator"
iam:
  codebuildRole:
    principalServices:
      - "codebuild"
    allowActions:
      s3:
        actions:
          - 'GetObject'
          - 'GetBucket'
          - 'List*'
          - 'DeleteObject'
          - 'Abort'
          - 'PutObject'
        resources:
          - '*'
      codecommit:
        actions:
          - '*'
        resources:
          - '*'
      sts:
        actions:
          - 'AssumeRole'
        resources:
          - '*'
      codepipeline:
        actions:
          - 'GetPipelineState'
          - 'PutApprovalResult'
        resources:
          - '*'
sources:
  - id: "orchestrator"
    repositoryName: "cai-llm-orchestrator-service"
codebuilds:
  - projectName: "deploy"
    buildSpecYaml: "deploy.yaml"
codePipelines:
  - pipelineName: "dev-tom"
    trigger:
      id: "dev-tom"
      detailType:
        - "CodeCommit Repository State Change"
      repositories:
        - "bot-config"
      detail:
        referenceName:
          - prefix: "prefix/"
            suffix: "suffix"
          - "branch-name"
        referenceType:
          - "branch"
          - "tag"
        event:
          - "referenceCreated"
          - "referenceUpdated"
    stages:
      - stageName: "source"
        actions:
          - name: "source"
            type: "source"
            configuration:
              repositoryId: "orchestrator"
              branch: "main-fc"
      - stageName: "test"
        actions:
          - name: "test"
            type: "codebuild"
            configuration:
              type: 1
              projectName: "test"
              inputArtifact: "source"
      - stageName: "approval"
        actions:
          - name: "approve"
            type: "approval"
      - stageName: "build"
        actions:
          - name: "build"
            type: "codebuild"
            configuration:
              projectName: "deploy"
              inputArtifact: "source"
    variables:
      - name: "ENV"
        value: "dev-tom"
