version: 0.2

phases:
  build:
    commands:
      - echo "auto-deploy"
      - |
        if [ "$AUTO_APPROVAL" != "true" ]; then
          echo "AUTO_APPROVAL is disable. Ending the process."
        else
          echo "AUTO_APPROVAL - $AUTO_APPROVAL enabled. auto approving"
          status_res=$(aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[?stageName==`approval`]')
          status=$(echo $status_res | jq -r '.[] | select(.stageName=="approval") | .actionStates[] | select(.actionName=="approval") | .latestExecution.status')
          if [ "$status" != "InProgress" ]; then
            echo "Incorrect latestExecution status, please approve the action manually"
          else 
            token=$(echo $status_res | jq -r '.[] | select(.stageName=="approval") | .actionStates[] | select(.actionName=="approval") | .latestExecution.token')
            echo "{
              \"pipelineName\": \"$PIPELINE_NAME\",
              \"stageName\": \"$PIPELINE_STAGE_NAME\",
              \"actionName\": \"$PIPELINE_ACTION_NAME\",
              \"token\": \"$token\",
              \"result\": {
                \"status\": \"Approved\",
                \"summary\": \"Pipeline auto approve action\"
              }
            }" > approvalstage-approved.json
            cat approvalstage-approved.json
            aws codepipeline put-approval-result --cli-input-json file://approvalstage-approved.json
            if [ $? -ne 0 ]; then
              echo "Error occurred while executing aws codepipeline put-approval-result please approve the action manually"
            else
              echo "Command executed successfully"
            fi
          fi
        fi
