version: 0.2

env:
  git-credential-helper: yes

phases:
  pre_build:
    commands:
      - echo "build post test"
      - echo $TARGET_BRANCH
      - git checkout $TARGET_BRANCH
      - npm i
  build:
    commands:
      - npm run test:coverage
